# Threshold values for alert_manager
cpu_percent_max       25.0
ram_percent_max       40.0
swap_percent_max      50.0
disk_percent_max      80.0
net_rx_kbps_max       2048.0
net_tx_kbps_max       2048.0
load_1min_max         2.5
